export const INGREDIENTS_CONFIG = [
	'Abborre',
	'Alaska pollock',
	'Ananas',
	'Ansjovis skarpsill konserv. ',
	'Apelsin',
	'Apelsinskal',
	'Aprikos',
	'Aronia',
	'Aronia slånaronia',
	'Banan',
	'Bananchips',
	'Korn',
	'Spelt',
	'Graham',
	'Sirap',
	'Ägg',
	'Äggula',
	'Äggvita',
	'Soja',
	'Sojabönor',
	'Tofu',
	'Björnbär',
	'Bläckfisk',
	'Blåbär',
	'Blåmussla',
	'Bordsmargarin',
	'Braxen',
	'Brown sauce',
	'Brun farin',
	'Böckling',
	'Böckling dubbelfilé',
	'Carambole',
	'Cashewnötter',
	'Cherimoya',
	'Chiafrö',
	'Chilinötter',
	'Chilisås',
	'Citron',
	'Citronskal',
	'Clementin',
	'Dadlar',
	'Druvkärnolja',
	'Druvsocker',
	'Fikon',
	'Fiskbuljong',
	'Fiskpinnar',
	'Flundra',
	'Flytande',
	'Flytande margarin',
	'Fläderbär',
	'Frityrolja',
	'Frukt torkad',
	'Fruktcocktail',
	'Fruktsocker',
	'Glykossirap',
	'Gojibär',
	'Granatäpple',
	'Grapefrukt',
	'Grillsås',
	'Gris ister',
	'Gris späck',
	'Grönsaksbuljong',
	'Guava',
	'Guldsparid',
	'Gurkmeja',
	'Gädda',
	'Gös',
	'Hallon',
	'Hamburgerdressing',
	'Hampafrö',
	'Hampafröolja',
	'Hasselnötter',
	'Havsabborre',
	'Havskräfta',
	'Havtorn',
	'Hjortron',
	'Hoki',
	'Honung',
	'Honungsmelon',
	'Hummer',
	'Bacon',
	'Fläskfilé',
	'Fläskkotlett',
	'Hushållsmargarin',
	'Hushållsmargarin mjölkfri',
	'Hälleflundra',
	'Hälleflundra vild',
	'Hönsbuljong',
	'Jordgubbar',
	'Jordnötter',
	'Kakao',
	'Kakaobönor',
	'Kakaosmör',
	'Kaktusfikon',
	'Kalvbuljong',
	'Kapkummel',
	'Kardemumma',
	'Kastanjer',
	'Katrinplommon',
	'Ketchup',
	'Kiwi',
	'Kokosfett',
	'Kokosflingor',
	'Kokosmjölk',
	'Kokosnöt',
	'Kokosolja',
	'Kolja',
	'Koriander',
	'Krabba',
	'Krusbär',
	'Kryddblandning taco',
	'Kryddnejlika',
	'Kräfta',
	'Kummel',
	'Kumquat',
	'Kvitten',
	'Körsbär',
	'Köttbuljong',
	'Lake',
	'Lax gravad',
	'Lax kallrökt',
	'Lax rimmad',
	'Lax urtagen',
	'Lime',
	'Linfrö',
	'Linfröolja',
	'Lingon',
	'Litchi',
	'Ljus sirap',
	'Lutfisk',
	'Macadamianötter',
	'Majsolja',
	'Makrill',
	'Mandarin',
	'Mandelmassa',
	'Mandelmjöl',
	'Mango',
	'Marulk',
	'Matfettsblandning',
	'Mullbär',
	'Muskotnöt',
	'Nektarin',
	'Nypon',
	'Nätmelon',
	'Nöt talg',
	'Odon',
	'Olivolja',
	'Ostron',
	'Palmolja',
	'Pangasiusmal',
	'Papaya',
	'Papaya torkad',
	'Paradisäpple',
	'Paranötter',
	'Passionsfrukt',
	'Pekannötter',
	'Persika',
	'Persika torkad',
	'Physalis',
	'Piggvar',
	'Pilgrimsmussla',
	'Pinjefrö',
	'Pinklax',
	'Pistaschnötter',
	'Plommon',
	'Psylliumfröskal',
	'Pumpafrö',
	'Päron',
	'Päron torkade',
	'Rabarber',
	'Rapsolja',
	'Regnbågslax',
	'Russin',
	'Råg',
	'Röding',
	'Rödspätta',
	'Rönnbär',
	'Salt havssalt u. jod',
	'Salt m. jod',
	'Salt mineralsalt',
	'Salt u. jod',
	'Salt örtsalt',
	'Saltsill',
	'Saltströmming',
	'Selleri',
	'Rotselleri',
	'Sardeller konserv.',
	'Sardiner i olja konserv.',
	'Satsumas',
	'Sej',
	'Senap',
	'Sesam',
	'Lupin',
	'Snäcka',
	'Mussla',
	'Sesamfrö',
	'Sesamolja',
	'Sharon',
	'Sik',
	'Siklöja',
	'Sill',
	'Skinkbuljong',
	'Smör fett',
	'Snabbkaffe pulver',
	'Snigel',
	'Socker',
	'Sojaolja',
	'Sojasås',
	'Solrosfrö',
	'Solrosolja',
	'Sorbitol',
	'Spiskummin',
	'Strömming',
	'Strömmingsflundra',
	'Surimi',
	'Surkörsbär',
	'Surströmming',
	'Sweet chilisås',
	'Sötkörsbär',
	'Sötmandel',
	'Tangerin',
	'Teriyakisås',
	'Tilapia',
	'Tistelolja',
	'Tonfisk',
	'Torsk',
	'Tranbär',
	'Vallmofrö',
	'Valnötter',
	'Vattenmelon',
	'Vete',
	'Vetegroddsolja',
	'Vinbär röda',
	'Vinbär svarta',
	'Vinbär vita',
	'Vindruvor',
	'Vindruvor gröna',
	'Vindruvor röda',
	'Vinäger',
	'Vitling',
	'Wasabi',
	'Äppelcidervinäger',
	'Äpple',
	'Äpple torkat',
	'Ättiksprit',
	'Ättikströmming',
	'Ål',
	'Öring',
	'Öring Sverige',
	'Öring odlad',
] as const;
