export const INGREDIENTS = [
	'Abborre',
	'Alaska pollock',
	'Ananas',
	'Ansjovis',
	'Apelsin',
	'Apelsinskal',
	'Aprikos',
	'Aronia',
	'Aronia slånaronia',
	'Bacon',
	'Banan',
	'Bananchips',
	'Biff',
	'Björnbär',
	'Bläckfisk',
	'Blåbär',
	'Blåmussla',
	'Bordsmargarin',
	'Braxen',
	'Brown sauce',
	'Brun farin',
	'Böckling',
	'Böckling dubbelfilé',
	'Carambole',
	'Cashewnötter',
	'Cherimoya',
	'Chiafrö',
	'Chilinötter',
	'Chilisås',
	'Citron',
	'Citronskal',
	'Clementin',
	'Dadlar',
	'Druvkärnolja',
	'Druvsocker',
	'Fikon',
	'Fiskbuljong',
	'Fiskpinnar',
	'Flundra',
	'Flytande margarin',
	'Fläderbär',
	'Fläskfilé',
	'Fläskkotlett',
	'Frityrolja',
	'Frukt torkad',
	'Fruktcocktail',
	'Fruktsocker',
	'Glykossirap',
	'Gojibär',
	'Graham',
	'Granatäpple',
	'Grapefrukt',
	'Grillsås',
	'Gris ister',
	'Gris späck',
	'Grönsaksbuljong',
	'Guava',
	'Guldsparid',
	'Gurkmeja',
	'Gädda',
	'Gös',
	'Hallon',
	'Hamburgerdressing',
	'Hampafrö',
	'Hampafröolja',
	'Hasselnötter',
	'Havsabborre',
	'Havskräfta',
	'Havtorn',
	'Hjortron',
	'Hoki',
	'Honung',
	'Honungsmelon',
	'Hummer',
	'Hushållsmargarin',
	'Hushållsmargarin mjölkfri',
	'Hälleflundra',
	'Hälleflundra vild',
	'Hönsbuljong',
	'Jordgubbar',
	'Jordnötter',
	'Kakao',
	'Kakaobönor',
	'Kakaosmör',
	'Kaktusfikon',
	'Kalvbuljong',
	'Kapkummel',
	'Kardemumma',
	'Kastanjer',
	'Katrinplommon',
	'Ketchup',
	'Kiwi',
	'Kokosfett',
	'Kokosflingor',
	'Kokosmjölk',
	'Kokosnöt',
	'Kokosolja',
	'Kolja',
	'Koriander',
	'Korn',
	'Krabba',
	'Krusbär',
	'Kryddblandning taco',
	'Kryddnejlika',
	'Kräfta',
	'Kummel',
	'Kumquat',
	'Kvitten',
	'Körsbär',
	'Köttbuljong',
	'Lake',
	'Lax gravad',
	'Lax kallrökt',
	'Lax rimmad',
	'Lax urtagen',
	'Lime',
	'Linfrö',
	'Linfröolja',
	'Lingon',
	'Litchi',
	'Ljus sirap',
	'Lupin',
	'Lutfisk',
	'Macadamianötter',
	'Majsolja',
	'Makrill',
	'Mandarin',
	'Mandelmassa',
	'Mandelmjöl',
	'Mango',
	'Marulk',
	'Matfettsblandning',
	'Mullbär',
	'Muskotnöt',
	'Mussla',
	'Nektarin',
	'Nypon',
	'Nätmelon',
	'Nötfärs',
	'Nötkött',
	'Nöt talg',
	'Odon',
	'Olivolja',
	'Ostron',
	'Palmolja',
	'Pangasiusmal',
	'Papaya',
	'Papaya torkad',
	'Paradisäpple',
	'Paranötter',
	'Passionsfrukt',
	'Pekannötter',
	'Persika',
	'Persika torkad',
	'Physalis',
	'Piggvar',
	'Pilgrimsmussla',
	'Pinjefrö',
	'Pinklax',
	'Pistaschnötter',
	'Plommon',
	'Psylliumfröskal',
	'Pumpafrö',
	'Päron',
	'Päron torkade',
	'Rabarber',
	'Rapsolja',
	'Regnbågslax',
	'Rotselleri',
	'Russin',
	'Råg',
	'Röding',
	'Rödspätta',
	'Rönnbär',
	'Salt havssalt u. jod',
	'Salt m. jod',
	'Salt mineralsalt',
	'Salt u. jod',
	'Salt örtsalt',
	'Saltsill',
	'Saltströmming',
	'Sardeller konserv.',
	'Sardiner i olja konserv.',
	'Satsumas',
	'Sej',
	'Selleri',
	'Senap',
	'Sesam',
	'Sesamfrö',
	'Sesamolja',
	'Sharon',
	'Sik',
	'Siklöja',
	'Sill',
	'Sirap',
	'Skinkbuljong',
	'Smör fett',
	'Snabbkaffe pulver',
	'Snigel',
	'Snäcka',
	'Socker',
	'Soja',
	'Sojabönor',
	'Sojaolja',
	'Sojasås',
	'Solrosfrö',
	'Solrosolja',
	'Sorbitol',
	'Spelt',
	'Spiskummin',
	'Strömming',
	'Strömmingsflundra',
	'Surimi',
	'Surkörsbär',
	'Surströmming',
	'Sweet chilisås',
	'Sötkörsbär',
	'Sötmandel',
	'Tangerin',
	'Teriyakisås',
	'Tilapia',
	'Tistelolja',
	'Tofu',
	'Tonfisk',
	'Torsk',
	'Tranbär',
	'Vallmofrö',
	'Valnötter',
	'Vattenmelon',
	'Vete',
	'Vetegroddsolja',
	'Vinbär röda',
	'Vinbär svarta',
	'Vinbär vita',
	'Vindruvor',
	'Vindruvor gröna',
	'Vindruvor röda',
	'Vinäger',
	'Vitling',
	'Wasabi',
	'Ägg',
	'Äggula',
	'Äggvita',
	'Äppelcidervinäger',
	'Äpple',
	'Äpple torkat',
	'Ättiksprit',
	'Ättikströmming',
	'Ål',
	'Öring',
	'Öring odlad',
	'Mjölk',
	'Grädde',
] as const;

export const INGREDIENT_CATEGORIES = [
	'BaljväxterOchSvamp',
	'Buljonger',
	'BrödOchSpannmål',
	'BärOchFrukt',
	'Fett',
	'Fisk',
	'Fläsk',
	'Frukt',
	'Grönsaker',
	'Mjölkprodukter',
	'NötterOchFrön',
	'Nötkött',
	'Skaldjur',
	'SockerOchSötningsmedel',
	'ÄggOchRomOchKaviar',
	'Övrigt',
] as const;

export type Ingredient = (typeof INGREDIENTS)[number];
export type IngredientCategory = (typeof INGREDIENT_CATEGORIES)[number];

export const INGREDIENTS_BY_CATEGORY: Record<IngredientCategory, Ingredient[]> =
	{
		BaljväxterOchSvamp: ['Soja', 'Sojabönor', 'Sojasås', 'Tofu'],
		Buljonger: ['Fiskbuljong', 'Köttbuljong', 'Hönsbuljong', 'Kalvbuljong'],
		BrödOchSpannmål: ['Graham', 'Korn', 'Råg', 'Spelt', 'Vete'],
		BärOchFrukt: [
			'Ananas',
			'Aprikos',
			'Aronia',
			'Aronia slånaronia',
			'Björnbär',
			'Blåbär',
			'Hallon',
			'Havtorn',
			'Jordgubbar',
			'Nypon',
			'Rönnbär',
			'Tranbär',
			'Vinbär röda',
			'Vinbär svarta',
			'Vinbär vita',
			'Carambole',
			'Fläderbär',
			'Frukt torkad',
			'Fruktcocktail',
			'Gojibär',
			'Grapefrukt',
			'Guava',
			'Kaktusfikon',
			'Kumquat',
			'Kvitten',
			'Litchi',
			'Papaya',
			'Papaya torkad',
			'Physalis',
			'Satsumas',
			'Sharon',
			'Surkörsbär',
			'Sötkörsbär',
			'Tangerin',
		],
		Fett: [
			'Bordsmargarin',
			'Druvkärnolja',
			'Frityrolja',
			'Hushållsmargarin mjölkfri',
			'Kakaosmör',
			'Kokosfett',
			'Kokosolja',
			'Kolja',
			'Majsolja',
			'Olivolja',
			'Palmolja',
			'Rapsolja',
			'Sardiner i olja konserv.',
			'Sesamolja',
			'Sojaolja',
			'Solrosolja',
			'Tistelolja',
			'Vetegroddsolja',
		],
		Fisk: [
			'Abborre',
			'Alaska pollock',
			'Ansjovis',
			'Bläckfisk',
			'Fiskbuljong',
			'Fiskpinnar',
			'Havsabborre',
			'Hälleflundra',
			'Hälleflundra vild',
			'Lax gravad',
			'Lax kallrökt',
			'Lax rimmad',
			'Lax urtagen',
			'Lutfisk',
			'Makrill',
			'Pinklax',
			'Regnbågslax',
			'Röding',
			'Saltsill',
			'Sej',
			'Siklöja',
			'Sill',
			'Tonfisk',
			'Torsk',
			'Vitling',
			'Öring',
			'Braxen',
			'Chilisås',
			'Flundra',
			'Grillsås',
			'Guldsparid',
			'Gädda',
			'Gös',
			'Hoki',
			'Kapkummel',
			'Kummel',
			'Pangasiusmal',
			'Piggvar',
			'Rödspätta',
			'Saltströmming',
			'Sik',
			'Strömming',
			'Strömmingsflundra',
			'Surströmming',
			'Sweet chilisås',
			'Teriyakisås',
			'Tilapia',
			'Ättikströmming',
			'Ål',
		],
		Fläsk: ['Bacon', 'Fläskfilé', 'Fläskkotlett', 'Gris ister', 'Gris späck'],
		Frukt: [
			'Apelsin',
			'Apelsinskal',
			'Banan',
			'Bananchips',
			'Citron',
			'Citronskal',
			'Clementin',
			'Dadlar',
			'Fikon',
			'Granatäpple',
			'Honungsmelon',
			'Katrinplommon',
			'Kiwi',
			'Lime',
			'Mango',
			'Nätmelon',
			'Paradisäpple',
			'Passionsfrukt',
			'Persika',
			'Persika torkad',
			'Plommon',
			'Päron',
			'Päron torkade',
			'Vattenmelon',
			'Äpple',
			'Äpple torkat',
		],
		Grönsaker: ['Rabarber', 'Rotselleri', 'Selleri'],
		Mjölkprodukter: [
			'Bordsmargarin',
			'Flytande margarin',
			'Hushållsmargarin',
			'Matfettsblandning',
			'Smör fett',
			'Vetegroddsolja',
			'Mjölk',
			'Grädde',
		],
		Nötkött: ['Biff', 'Kalvbuljong', 'Köttbuljong', 'Nötfärs', 'Nötkött'],

		NötterOchFrön: [
			'Cashewnötter',
			'Chiafrö',
			'Chilinötter',
			'Hampafrö',
			'Hampafröolja',
			'Hasselnötter',
			'Jordnötter',
			'Kokosnöt',
			'Marulk',
			'Krusbär',
			'Körsbär',
			'Lingon',
			'Mandarin',
			'Mullbär',
			'Nektarin',
			'Linfrö',
			'Linfröolja',
			'Macadamianötter',
			'Mandelmassa',
			'Mandelmjöl',
			'Muskotnöt',
			'Nöt talg',
			'Paranötter',
			'Pekannötter',
			'Pinjefrö',
			'Pistaschnötter',
			'Psylliumfröskal',
			'Pumpafrö',
			'Sesamfrö',
			'Solrosfrö',
			'Sötmandel',
			'Vallmofrö',
			'Valnötter',
		],
		Skaldjur: [
			'Blåmussla',
			'Havskräfta',
			'Hummer',
			'Krabba',
			'Kräfta',
			'Mussla',
			'Ostron',
			'Pilgrimsmussla',
			'Snäcka',
			'Surimi',
		],
		SockerOchSötningsmedel: [
			'Brun farin',
			'Druvsocker',
			'Fruktsocker',
			'Glykossirap',
			'Honung',
			'Ljus sirap',
			'Sirap',
			'Socker',
			'Sorbitol',
		],
		ÄggOchRomOchKaviar: ['Ägg', 'Äggula', 'Äggvita'],

		Övrigt: [
			'Brown sauce',
			'Böckling',
			'Böckling dubbelfilé',
			'Cherimoya',
			'Hjortron',
			'Kakao',
			'Kakaobönor',
			'Kastanjer',
			'Kokosflingor',
			'Kokosmjölk',
			'Lake',
			'Lupin',
			'Odon',
			'Russin',
			'Salt havssalt u. jod',
			'Salt m. jod',
			'Salt mineralsalt',
			'Salt u. jod',
			'Salt örtsalt',
			'Sardeller konserv.',
			'Sesam',
			'Snabbkaffe pulver',
			'Snigel',
			'Vindruvor',
			'Vindruvor gröna',
			'Vindruvor röda',
			'Wasabi',
		],
	} as const;
