export const INGREDIENT_CATEGORIES_CONFIG = [
	'Alkohol',
	'Fett',
	'Frukt',
	'Fläsk',
	'Bär',
	'Grönsaker',
	'Rotfrukter',
	'Kryddor',
	'Örter',
	'Nötkött',
	'Kyckling, fågel',
	'Fisk',
	'Skaldjur',
	'Mjölkprodukter',
	'Ost',
	'Ägg, rom, kaviar',
	'Lever, njure, tunga etc.',
	'Baljväxter och svamp',
	'Bröd och spannmål',
	'Potatis och pasta',
	'Socker och sötningsmedel',
	'Nötter, frön',
	'Korn',
	'Övrigt',
] as const;
