import { Meal } from '@/types/Meal';

export const mockMeals: Meal[] = [
	{
		_id: 'b0c0a035-4b2b-4390-8988-01dc6e173650',
		name: 'Kryddig Kikärtsgryta',
		description: 'Het vegansk gryta med marockanska kryddor.',
		image: '/assets/kikärtsgryta.jpg',
		ingredients: ['Äpple', 'Blåbär', 'Kyckling', 'Chili'],
		location: 'Göteborgs Centralstation',
		expirationDate: '2025-05-13',
		isMine: true,
	},
	{
		_id: 'd27461e9-d318-4fff-aa3d-9222e6be486e',
		name: 'Glutenfria Bananpannkakor',
		description: 'Mjuka, fluffiga pannkakor utan gluten.',
		image: '/assets/bananpannkakor.jpg',
		ingredients: ['Majs', 'Kål', 'Zucchini', 'Couscous'],
		location: 'Hisingen Matbank',
		expirationDate: '2025-05-09',
		isMine: false,
	},
	{
		_id: 'bd2d04de-158c-4a69-8d98-0607b705943f',
		name: 'Laxpasta med Dill',
		description: 'Krämig pasta med färsk dill och rökt lax.',
		image: '/assets/laxpasta.png',
		ingredients: ['Lök', 'Lax', 'Kål', 'Zucchini'],
		location: 'Lundby Park',
		expirationDate: '2025-05-12',
		isMine: false,
	},
	{
		_id: '7016ad4c-49a7-483b-8b25-e0f5e1b610f8',
		name: 'Veganska Burritos',
		description: 'Fyllda med svarta bönor, ris och lime.',
		image: '/assets/veganska-burritos.jpg',
		ingredients: ['Banan', 'Pasta', 'Ägg', 'Äpple'],
		location: 'Malmö Gatukök',
		expirationDate: '2025-05-11',
		isMine: false,
	},
	{
		_id: '3094d23d-d11d-4469-aadd-b5f43a1f67a7',
		name: 'Halal Kycklingcurry',
		description: 'Mild kokoskyckling serverad med ris.',
		image: '/assets/Kycklingcurry.jpg',
		ingredients: ['Morot', 'Banan', 'Kikärter', 'Äpple'],
		location: 'Angereds Moské',
		expirationDate: '2025-05-12',
		isMine: true,
	},
	{
		_id: '3bc5b48a-82f4-4e99-a695-6c5de9fc3ea0',
		name: 'Äggmackor',
		description: 'Klassisk äggsallad på rågbröd.',
		image: '/assets/Äggmackor.jpg',
		ingredients: ['Zucchini', 'Jordgubbar', 'Äpple', 'Banan'],
		location: 'Frölunda Centrum',
		expirationDate: '2025-05-09',
		isMine: false,
	},
	{
		_id: '442c1614-7da9-4a66-85e2-8447a1c89c42',
		name: 'Fruktlåda',
		description: 'Blandad färsk fruktlåda med äpple, banan och bär.',
		image: '/assets/Fruktlåda.jpg',
		ingredients: ['Citronskal', 'Blåbär', 'Chili', 'Svarta bönor'],
		location: 'Östra Sjukhuset',
		expirationDate: '2025-05-13',
		isMine: false,
	},
	{
		_id: '605d8fb0-a66f-469d-a00d-888717aa02e3',
		name: 'Linssoppa',
		description: 'Röda linser kokta med vitlök och lök.',
		image: '/assets/Linsoppa.jpg',
		ingredients: ['Pasta', 'Blåbär', 'Fisk', 'Lök'],
		location: 'Järntorget Station',
		expirationDate: '2025-05-14',
		isMine: false,
	},
	{
		_id: 'bfa8f9f9-6fb3-4463-94f1-275ccdb61cdb',
		name: 'Kycklingwraps',
		description: 'Halal kyckling med sallad och yoghurtsås.',
		image: '/assets/Kycklingwraps.jpg',
		ingredients: ['Lök', 'Tofu', 'Banan', 'Fisk'],
		location: 'Backaplan Hjälpcenter',
		expirationDate: '2025-05-10',
		isMine: false,
	},
	{
		_id: '51384326-4b63-4767-b96f-aefd5431232d',
		name: 'Vegansk Chili',
		description: 'Långkokta bönor med tomat och chili.',
		image: '/assets/Vegansk Chili.jpg',
		ingredients: ['Tofu', 'Pasta', 'Zucchini', 'Kål'],
		location: 'Kortedala Delningskök',
		expirationDate: '2025-05-13',
		isMine: false,
	},
	{
		_id: '9b9ccae6-a72f-4291-a9a2-fd22d9da3d25',
		name: 'Skaldjurspaella',
		description: 'Spansk paella med räkor och musslor.',
		image: '/assets/Skaldjurspaella.jpg',
		ingredients: ['Tofu', 'Dill', 'Rågbröd', 'Fisk'],
		location: 'Majorna Upphämtning',
		expirationDate: '2025-05-14',
		isMine: false,
	},
	{
		_id: '2012c151-1494-41e2-8d0f-7ad75c5bd5c1',
		name: 'Tofuwok',
		description: 'Söt och het wok med tofu och grönsaker.',
		image: '/assets/Tofuwok.jpg',
		ingredients: ['Ost', 'Pasta', 'Rågbröd', 'Zucchini'],
		location: 'Gamlestaden Matdelning',
		expirationDate: '2025-05-12',
		isMine: false,
	},
	{
		_id: 'fa111b49-5ede-490e-abdd-a1871fc44794',
		name: 'Pasta Pesto',
		description: 'Pasta med färsk basilika och körsbärstomater.',
		image: '/assets/Pasta-Pesto.jpg',
		ingredients: ['Couscous', 'Kikärter', 'Ost', 'Räka'],
		location: 'Högsbo Bistånd',
		expirationDate: '2025-05-12',
		isMine: false,
	},
	{
		_id: '1c1e3ed7-ce58-4f2e-89bb-00772ae979ac',
		name: 'Thai Curry',
		description: 'Röd curry med kokosmjölk och risnudlar.',
		image: '/assets/Thai-Curry.jpg',
		ingredients: ['Grädde', 'Morot', 'Ris', 'Tomat'],
		location: 'Linné Delningspunkt',
		expirationDate: '2025-05-14',
		isMine: false,
	},
	{
		_id: 'bec43a90-fd2d-4aad-8732-757980d86951',
		name: 'Sushilåda',
		description: 'Blandad sushi med avokado, lax och gurka.',
		image: '/assets/Sushilåda.jpg',
		ingredients: ['Blåbär', 'Lök', 'Citronskal', 'Kål'],
		location: 'Nordstan Matstöd',
		expirationDate: '2025-05-11',
		isMine: false,
	},
	{
		_id: 'a9253348-bbc6-48b1-873e-73cf9a845d48',
		name: 'Avokadomacka',
		description: 'Rostat surdegsbröd med avokado och chili.',
		image: '/assets/Avokadomacka.jpg',
		ingredients: ['Ägg', 'Jordgubbar', 'Ost', 'Kyckling'],
		location: 'Masthugget Popup',
		expirationDate: '2025-05-09',
		isMine: false,
	},
	{
		_id: '9e512410-a900-445c-a707-47b8d847c988',
		name: 'Fisktacos',
		description: 'Grillad vit fisk med kål och lime.',
		image: '/assets/Fisktacos.jpg',
		ingredients: ['Gurka', 'Majs', 'Morot', 'Tomat'],
		location: 'Biskopsgården Truck',
		expirationDate: '2025-05-13',
		isMine: false,
	},
	{
		_id: '3d87bcde-7ab9-4dab-993a-bbe3ab75a0d1',
		name: 'Couscoussallad',
		description: 'Couscous med rostade grönsaker och citron.',
		image: '/assets/Couscoussallad.jpg',
		ingredients: ['Äpple', 'Kål', 'Couscous', 'Gurka'],
		location: 'Redbergsplatsen',
		expirationDate: '2025-05-13',
		isMine: false,
	},
	{
		_id: 'd2173bc8-074d-4378-88c2-ae2669901615',
		name: 'Biff Stroganoff',
		description: 'Krämig biffgryta med pasta.',
		image: '/assets/Biff-Stroganoff.jpg',
		ingredients: ['Ägg', 'Chili', 'Zucchini', 'Äpple'],
		location: 'Kålltorp BoxDrop',
		expirationDate: '2025-05-12',
		isMine: false,
	},
	{
		_id: '1e4a6a7e-2e88-4d8b-abda-ad30d4ab34fb',
		name: 'Äggfri Grönsakspaj',
		description: 'Mjuk paj med grönsaker, helt utan ägg.',
		image: '/assets/Äggfri Grönsakspaj.jpg',
		ingredients: ['Tofu', 'Tomat', 'Räka', 'Banan'],
		location: 'Slottskogen DelaMat',
		expirationDate: '2025-05-13',
		isMine: false,
	},
];
